- sections:
    - title: Introduction
      sections:
        - title: Contact Studio Support
          link: docs/introduction/contact-us.md
- sections:
    - title: Getting Started
      link: docs/getting-started.md
      sections:
        - title: Setup New Tenant
          link: docs/getting-started/setup-tenant/setup-tenant.md
        - title: Deploy New Tenant
          link: docs/getting-started/setup-tenant/deploy-tenant.md
        - title: Register New Tenant
          link: docs/getting-started/setup-tenant/register-tenant.md
        - title: Code New Tenant
          link: docs/getting-started/code-a-tenant/code-tenant.md
        - title: Preview & Publish Content
          link: docs/getting-started/preview-and-publish-content/preview-and-publish.md
- sections:
    - title: Gated Content
      link: docs/Spec_Testing/gatedContent.md
      # open: true  
      sections:
      - title: Gated Content Testing
        link: docs/Spec_Testing/gatedContent.md 
      # access: public
      # groups: []
- sections:
    - title: Resources
      sections:
        - title: API Guidelines
          link: docs/resources/guides/api-guide.md
        - title: How it works
          link: docs/resources/guides/how-to-use-stoplight.md
        - title: Learn how to use Prism Stoplight
          link: docs/resources/guides/how-to-use-stoplight.md
        - title: Learn how to use DocIgnore
          link: docs/resources/guides/how-to-use-docignore.md
        - title: Tutorials
          link: docs/resources/guides/how-to-use-docignore.md
          sections:
            - title: Markdown Support Guide
              link: docs/resources/markdown-support.md
              sections:
                - title: Card Support
                  link: docs/tutorials/markdown/card.md
                - title: Tabs Support
                  link: docs/tutorials/markdown/tabs.md
        - title: FAQ
          link: docs/faq/faq.md

        - title: Testing
          open: true
          sections: 
            - title: TestingDocs
              link: docs/SpecTest/SpecTest.md
              access: public
              groups: []
