name: GitHub Remote
on:
  # Triggers the workflow on push or pull request events but only for the dev , stage and main branch
  push:
    branches: [ develop,stage,main ]
  pull_request:
    branches: [ develop,stage,main ]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}." 
      - name: Creating new temp dir called tools
        run: |
         mkdir -m 777 tools
         cd tools
         pwd
         ls -la
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
         repository: Fiserv/remote-actions
         ref: develop
         path: ${{ github.workspace }}/tools
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
         repository: ${{ github.repository }}
         path: ${{ github.workspace }}
      - name: List files in the repository
        run: |
          cd ${{ github.workspace }}
          pwd
          ls -la
          cd ${{ github.workspace }}/tools
          pwd
          ls -la
      - name: Running YAML/Postman Zip Generator.....
        run: |
          pwd
          cd ${{ github.workspace }}/tools/scripts
          ls -la
          npmv=$(npm --version)
          echo "NPM version installed : " $npmv
          nodev=$(node --version)
          echo "Node version installed : " $nodev
          npm install
          echo " Repo: ${{ github.repository }}"
          echo " Space: ${{ github.workspace }}"
          result=$(npm run download ${{github.workspace }}/reference)
          echo "Test Results: \n"$result
          ls -la
          rm -rvf tools
          echo "After removing tools"
          pwd
          ls -la
          if [[ $result == *'YAML VALIDATOR / GENERARTOR FAILED'* ]] ;then
          echo "Validator failed and exiting the Job..."
          exit 1
          elif [[ $result == *'PASSED'* ]] ;then
          echo "Validator Ran Successfully....üçè"
          fi
      - run: echo "üçè This job's status is ${{ job.status }}."
      - name: Show file content
        run: |
          pwd
          ls -la
      - name: Commite changes from action runner to remote branch
        uses: stefanzweifel/git-auto-commit-action@v4
