name: GitHub Remote action
on:
  # Triggers the workflow on push or pull request events but only for the dev , stage and main branch
  push:
    branches: [ develop,stage,main ]
  pull_request:
    branches: [ develop,stage,main ]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@remote-action-flow
        with:
         repository: Fiserv/Test-repo
      - name: List files in the repository
        run: |
         pwd
         ls -la
